[workspace]
members = ["crates/wlang", "crates/wlang-web"]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[profile.release.package.playground]
opt-level = "s"
